# Generated by Django 5.1.5 on 2025-02-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Busqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_registro', models.IntegerField()),
                ('id_producto', models.IntegerField()),
                ('producto', models.CharField(max_length=150)),
                ('marca', models.CharField(max_length=150)),
                ('cantidad', models.IntegerField()),
                ('unidad_medida', models.CharField(max_length=10)),
                ('envase', models.CharField(max_length=150)),
                ('valor', models.IntegerField()),
                ('identificacion_url', models.CharField(max_length=500)),
                ('url', models.URLField()),
                ('fecha_extraccion', models.DateField()),
                ('pagina_general', models.URLField()),
            ],
        ),
    ]
