# Generated by Django 5.1.6 on 2025-02-13 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
